### ISSUE TITLE
Question re: image processing

### ISSUE THREAD

**Issue by bjornmeansbear** [bjornmeansbear/rwdf-site-theme#32]
Can we do mulitple size processing of the images — or at least down sample any that are over 1000px wide or something?

http://rwdf.cape.io/whatwedo/projects/digital-harbor/ 
is the worst offender...

and http://rwdf.cape.io/whatwedo/projects/masd-fellows/ has some large ones too...

It'd be better if this could happen automatically — Integrating this simply will be important for EZLE too...

**Comment by webmasterkai** [comment]
using `?size=l` in various 8laces
